"""push token unique per role

Revision ID: 1170df9bb61d
Revises: 03397471ed9e
Create Date: 2026-09-05 16:44:25.908342
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1170df9bb61d"
down_revision: Union[str, None] = "03397471ed9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_push_token_value", "push_tokens", type_="unique")
    op.create_unique_constraint(
        "uq_push_token_value_kind", "push_tokens", ["expo_push_token", "owner_kind"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_push_token_value_kind", "push_tokens", type_="unique")
    op.create_unique_constraint("uq_push_token_value", "push_tokens", ["expo_push_token"])
    # ### end Alembic commands ###
