"""mentor console presence, ended_by, reporter_kind

Revision ID: 2788b34bd299
Revises: c4191801fecf
Create Date: 2026-09-05 04:51:09.146565
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2788b34bd299"
down_revision: str | None = "c4191801fecf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    conversation_ended_by = sa.Enum("member", "listener", "system", name="conversationendedby")
    reporter_kind = sa.Enum("member", "listener", name="reporterkind")
    conversation_ended_by.create(bind, checkfirst=True)
    reporter_kind.create(bind, checkfirst=True)

    op.add_column(
        "listener_profiles",
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "conversations",
        sa.Column("ended_by", conversation_ended_by, nullable=True),
    )
    # server_default backfills existing rows as member-filed (they all are).
    op.add_column(
        "moderation_events",
        sa.Column(
            "reporter_kind",
            reporter_kind,
            nullable=False,
            server_default="member",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("moderation_events", "reporter_kind")
    op.drop_column("conversations", "ended_by")
    op.drop_column("listener_profiles", "last_seen_at")
    sa.Enum(name="reporterkind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="conversationendedby").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
