"""conversation reflections

Revision ID: 5e070c058a36
Revises: ff69c9001c14
Create Date: 2026-06-11 05:15:53.103930
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e070c058a36"
down_revision: str | None = "ff69c9001c14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_reflections",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", name="uq_reflection_conversation"),
    )
    op.create_index(
        op.f("ix_conversation_reflections_conversation_id"),
        "conversation_reflections",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_reflections_conversation_id"), table_name="conversation_reflections"
    )
    op.drop_table("conversation_reflections")
    # ### end Alembic commands ###
