"""chat profiles: public line, availability note, issue category, favourites

Revision ID: 61e06b08d4df
Revises: 1170df9bb61d
Create Date: 2026-09-06 16:08:19.242784
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61e06b08d4df"
down_revision: Union[str, None] = "1170df9bb61d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favourite_listeners",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("listener_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["listener_id"], ["listener_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "listener_id"),
    )
    op.add_column("conversations", sa.Column("issue_category", sa.String(length=40), nullable=True))
    op.add_column(
        "listener_profiles", sa.Column("public_line", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "listener_profiles", sa.Column("availability_note", sa.String(length=60), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listener_profiles", "availability_note")
    op.drop_column("listener_profiles", "public_line")
    op.drop_column("conversations", "issue_category")
    op.drop_table("favourite_listeners")
    # ### end Alembic commands ###
