"""path communities: user + listener community fields

Revision ID: 823180809488
Revises: 911d842dce97
Create Date: 2026-07-13 17:28:44.305954
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823180809488'
down_revision: Union[str, None] = '911d842dce97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listener_profiles', sa.Column('community_slug', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_listener_profiles_community_slug'), 'listener_profiles', ['community_slug'], unique=False)
    op.add_column('users', sa.Column('community_slug', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('journey_stage', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'journey_stage')
    op.drop_column('users', 'community_slug')
    op.drop_index(op.f('ix_listener_profiles_community_slug'), table_name='listener_profiles')
    op.drop_column('listener_profiles', 'community_slug')
    # ### end Alembic commands ###
