"""admin_accounts_audit

Revision ID: 911d842dce97
Revises: c7a91f4d2b58
Create Date: 2026-07-13 02:47:06.003849
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "911d842dce97"
down_revision: str | None = "c7a91f4d2b58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_accounts",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("role", sa.Enum("owner", "helper", name="adminrole"), nullable=False),
        sa.Column("status", sa.Enum("active", "revoked", name="adminstatus"), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_accounts_role"), "admin_accounts", ["role"], unique=False)
    op.create_index(op.f("ix_admin_accounts_status"), "admin_accounts", ["status"], unique=False)
    op.create_table(
        "admin_audit_log",
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("admin_name", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_audit_log_action"), "admin_audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_admin_audit_log_admin_id"), "admin_audit_log", ["admin_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admin_audit_log_admin_id"), table_name="admin_audit_log")
    op.drop_index(op.f("ix_admin_audit_log_action"), table_name="admin_audit_log")
    op.drop_table("admin_audit_log")
    op.drop_index(op.f("ix_admin_accounts_status"), table_name="admin_accounts")
    op.drop_index(op.f("ix_admin_accounts_role"), table_name="admin_accounts")
    op.drop_table("admin_accounts")
    # ### end Alembic commands ###
