"""safety_flags.stream_message_id

Revision ID: ac14868c5699
Revises: b34a2dc93a28
Create Date: 2026-06-08 20:31:13.472055
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac14868c5699"
down_revision: str | None = "b34a2dc93a28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "safety_flags", sa.Column("stream_message_id", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_safety_flags_stream_message_id"),
        "safety_flags",
        ["stream_message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_safety_flags_stream_message_id"), table_name="safety_flags")
    op.drop_column("safety_flags", "stream_message_id")
    # ### end Alembic commands ###
