"""initial schema

Revision ID: b34a2dc93a28
Revises: 
Create Date: 2026-06-08 19:53:37.654270
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34a2dc93a28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_user_id'), 'contributions', ['user_id'], unique=False)
    op.create_table('conversation_requests',
    sa.Column('kind', sa.Enum('general', 'personal', name='requestkind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'matched', 'declined', 'expired', name='requeststatus'), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('issue_category', sa.String(length=64), nullable=True),
    sa.Column('target_listener_id', sa.String(length=36), nullable=True),
    sa.Column('intro_message', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_requests_requester_id'), 'conversation_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_conversation_requests_status'), 'conversation_requests', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('type', sa.Enum('anon', 'mentoring', name='conversationtype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', 'wiped', name='conversationstatus'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('listener_id', sa.String(length=36), nullable=False),
    sa.Column('stream_channel_id', sa.String(length=128), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('status_mask', sa.String(length=32), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_listener_id'), 'conversations', ['listener_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('finance', 'mood', 'mentor_notes', 'gratitude', 'panda_wisdom', name='journalchannel'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_channel'), 'journal_entries', ['channel'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('listener_profiles',
    sa.Column('persona_name', sa.String(length=64), nullable=False),
    sa.Column('persona_avatar', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Enum('female', 'male', 'nonbinary', 'undisclosed', name='gender'), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('online', 'away', 'offline', name='listenerstatus'), nullable=False),
    sa.Column('vetting_status', sa.Enum('pending', 'approved', 'suspended', name='vettingstatus'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('active_conversations', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listener_profiles_persona_name'), 'listener_profiles', ['persona_name'], unique=False)
    op.create_index(op.f('ix_listener_profiles_status'), 'listener_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_listener_profiles_vetting_status'), 'listener_profiles', ['vetting_status'], unique=False)
    op.create_table('moderation_events',
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.Enum('redirect', 'warning', 'suspension', 'ban', name='moderationlevel'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_events_subject_id'), 'moderation_events', ['subject_id'], unique=False)
    op.create_table('safety_flags',
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('signal', sa.Enum('self_harm', 'suicidal', 'abuse', 'none', name='safetysignal'), nullable=False),
    sa.Column('matched_terms', sa.String(length=255), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_flags_conversation_id'), 'safety_flags', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_safety_flags_signal'), 'safety_flags', ['signal'], unique=False)
    op.create_index(op.f('ix_safety_flags_user_id'), 'safety_flags', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('persona_name', sa.String(length=64), nullable=False),
    sa.Column('persona_avatar', sa.String(length=64), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('age_at_signup', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('companion_animal', sa.String(length=32), nullable=True),
    sa.Column('companion_colour', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_persona_name'), 'users', ['persona_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_persona_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_safety_flags_user_id'), table_name='safety_flags')
    op.drop_index(op.f('ix_safety_flags_signal'), table_name='safety_flags')
    op.drop_index(op.f('ix_safety_flags_conversation_id'), table_name='safety_flags')
    op.drop_table('safety_flags')
    op.drop_index(op.f('ix_moderation_events_subject_id'), table_name='moderation_events')
    op.drop_table('moderation_events')
    op.drop_index(op.f('ix_listener_profiles_vetting_status'), table_name='listener_profiles')
    op.drop_index(op.f('ix_listener_profiles_status'), table_name='listener_profiles')
    op.drop_index(op.f('ix_listener_profiles_persona_name'), table_name='listener_profiles')
    op.drop_table('listener_profiles')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_channel'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_listener_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_conversation_requests_status'), table_name='conversation_requests')
    op.drop_index(op.f('ix_conversation_requests_requester_id'), table_name='conversation_requests')
    op.drop_table('conversation_requests')
    op.drop_index(op.f('ix_contributions_user_id'), table_name='contributions')
    op.drop_table('contributions')
    # ### end Alembic commands ###
