"""own chat: chat_messages + chat_read_markers (spike)

Revision ID: c0chat0spike1
Revises: d14b0step001
Create Date: 2026-09-20 04:34:38.069568
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0chat0spike1'
down_revision: Union[str, None] = 'd14b0step001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('crisis_signal', sa.String(length=32), nullable=True),
    sa.Column('redacted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sender_id', 'client_id', name='uq_chat_messages_client_id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_chat_messages_conversation_seq')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('chat_read_markers',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('reader_id', sa.String(length=36), nullable=False),
    sa.Column('last_read_seq', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'reader_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_read_markers')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
