"""listener applications

Revision ID: c0df67c15f95
Revises: 823180809488
Create Date: 2026-07-24 04:18:26.544890
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0df67c15f95'
down_revision: Union[str, None] = '823180809488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listener_applications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('communities', sa.JSON(), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mentor_interest', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='applicationstatus'), nullable=False),
    sa.Column('decline_reason', sa.String(length=255), nullable=True),
    sa.Column('listener_id', sa.String(length=36), nullable=True),
    sa.Column('pledge_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listener_applications_status'), 'listener_applications', ['status'], unique=False)
    op.create_index(op.f('ix_listener_applications_user_id'), 'listener_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listener_applications_user_id'), table_name='listener_applications')
    op.drop_index(op.f('ix_listener_applications_status'), table_name='listener_applications')
    op.drop_table('listener_applications')
    # ### end Alembic commands ###
