"""moderation_event review fields

Revision ID: ff69c9001c14
Revises: ac14868c5699
Create Date: 2026-06-09 02:16:41.115985
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff69c9001c14"
down_revision: str | None = "ac14868c5699"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any existing rows; new rows get the value from the ORM.
    op.add_column(
        "moderation_events",
        sa.Column("reviewed", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "moderation_events", sa.Column("reviewed_by", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_moderation_events_reviewed"), "moderation_events", ["reviewed"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_moderation_events_reviewed"), table_name="moderation_events")
    op.drop_column("moderation_events", "reviewed_by")
    op.drop_column("moderation_events", "reviewed")
    # ### end Alembic commands ###
